# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('as3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='classromm',
            new_name='classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='times',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(default=datetime.datetime(2015, 12, 28, 13, 48, 59, 977412, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
    ]
